<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OTAPI.Upcoming" Version="3.3.11" />
    <PackageReference Include="TSAPI" Version="6.1.0" />
    <PackageReference Include="TShock" Version="6.1.0" />
  </ItemGroup>


</Project>